[keyboard]
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mods = "Control|Shift"
