#!/bin/sh

# TheGreatMcPain's dotfiles install script. (requires stow)
#
# ./install stow   | (Install stow packages) DEFAULT
# ./install restow | (Restow stow packages)
# ./install adopt  | (Atopt stow packages)

# Create directory stucture
makedirs() {
    if ! [ -f "./install" ]; then
        echo "Not in root of repo."
        exit 1
    fi
    for d in $(find * -maxdepth 0 -type d); do
        cd $d
        find -type d | tail -n +2 | xargs -I{} mkdir -vp "../{}"
        cd ..
    done
}

# Install stow packages
install() {
    for d in $(find * -maxdepth 0 -type d); do
        stow -v -t ~/ -S $d
    done
}

# Adopt stow packages.
adopt() {
    for d in $(find * -maxdepth 0 -type d); do
        stow -v -t ~/ --adopt $d
    done
}

# Restow stow packages.
restow() {
    for d in $(find * -maxdepth 0 -type d); do
        stow -v -t ~/ -R $d
    done
}

if [ "$1"x = "stow"x ]; then
    install
elif [ "$1"x = "adopt"x ]; then
    adopt
elif [ "$1"x = "restow"x ]; then
    restow
elif [ "$1"x = "makedirs"x ]; then
    makedirs
else
    echo "Usage: ./install <stow,restow,adopt>"
    echo "    ./install stow      | (Install stow packages) DEFAULT"
    echo "    ./install restow    | (Restow stow packages)"
    echo "    ./install adopt     | (Atopt stow packages)"
    echo "    ./install makedirs  | (Create directory tree)"
fi
