#!/bin/sh
bspc rule -r "*"

# Background
bspwm_exec -a -e multilockscreen -o "-w"

# Keyboard Shortcuts
bspwm_exec -a -e sxhkd

# Pulseaudio
# pulseaudio -D

# Pipewire (Kill pulseaudio first if running)
pulseaudio --kill; gentoo-pipewire-launcher &

# Compositor
if which nvidia-settings >/dev/null; then
    bspwm_exec -e picom -o '-b --backend xrender'
else
    bspwm_exec -e picom -o '-b --vsync'
fi

# clears background windows when fullscreen.
bspwm_exec -e bspwm_cleanfullscreen -p 'bspwm_cleanfullscreen'

# Allows use of pkexec
bspwm_exec -e /usr/libexec/polkit-gnome-authentication-agent-1

# Stuff I normally will have on my Desktop/Laptop.
bspwm_exec -e unclutter
bspwm_exec -e dunst
bspwm_exec -e mpDris2
bspwm_exec -e qlipper

# Enable numlock
numlockx &

# Custom startup script.
~/.config/bspwm/startup

# Get cover art from current mpd song. to prevent
# errors when running music setup.
~/.config/ncmpcpp/art.sh

# Since I've made my sxhkd handle multi-monitors in
# a more portable way I can now give all monitors
# 10 desktops.
for m in $(bspc query --monitors --names); do
    bspc monitor $m -d 1 2 3 4 5 6 7 8 9 10
    bspc config -m $m top_padding 24
    bspc config -m $m bottom_padding 30
done

bspc config border_width         2
bspc config window_gap          16

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config pointer_follows_monitor true
#bspc config pointer_follows_focus true
#bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a MEGAsync manage=off
