#!/bin/sh
# Used to change workspaces in a multi-monitor setup.

activemonitorid=$(hyprctl monitors | grep -B 10 "focused: yes" | awk 'NR==1 {print $4}' | cut -c1)
currworkspace=$1

workspacemultiplier=$((activemonitorid*10))

destworkspace=$((workspacemultiplier+currworkspace))

hyprctl dispatch focusmonitor $activemonitorid
hyprctl dispatch workspace $destworkspace
