#!/bin/sh
# Used to change workspaces in a multi-monitor setup.

activemonitorid=$(hyprctl -j monitors | jq '.[] | select(.focused == true) | .id')
currworkspace=$1

workspacemultiplier=$((activemonitorid*10))

destworkspace=$((workspacemultiplier+currworkspace))

hyprctl dispatch focusmonitor $activemonitorid
hyprctl dispatch workspace $destworkspace
