#!/bin/sh

# Status Bar
# With temperature zone 2
~/.config/polybar/launch.sh 2 &

# I'm an attention whore.
bspwm_exec -e mpd_discord_richpresence -o '--no-idle'
bspwm_exec -e discordRichPresencePlex.py

# Other Things
bspwm_exec -e mpd
bspwm_exec -e syncthing -o '-no-browser -no-restart -logflags=0'
bspwm_exec -e megasync
bspwm_exec -e redshift-gtk
bspwm_exec -e dropbox
bspwm_exec -e steam -o '-silent %U'
bspwm_exec -e ckb-next -o '-b'
bspwm_exec -e hp-systray
#bspwm_exec -e slack -o '-u'
bspwm_exec -e discord-to-systray -p 'Discord'
bspwm_exec -e qbittorrent-to-systray -s 20 -p 'qbittorrent'
