#!/bin/sh

# Disable touchpad
toggle-touchpad disable

# Other Things
bspwm_exec -e megasync
bspwm_exec -e redshift-gtk
bspwm_exec -e steam -o '-silent %U'
bspwm_exec -e discord-to-systray -p 'Discord'
